# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Lint

on: [push, pull_request]

defaults:
  run:
    working-directory: ./backend-python/credito-express-app  

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - uses: actions/checkout@v2

      - name: Lint
        run: |
          pip install flake8
          flake8 main.py
